### ISSUE TITLE
Make sure that helpful info is available when step fails

### ISSUE THREAD

**Issue by AndreasEK** [valfirst/jbehave-junit-runner#15]
At a client today, a step failed when webdriver couldn't locate a certain element. The step was red in the JUnit view in eclipse, but no helpful details available.

**Comment by AndreasEK** [comment]
It would be nice to have a few more examples to reproduce...

**Comment by skurlow** [comment]
Don't you get useful info written to the console? I do. Can you provide an example of the issue or otherwise should you close this?
