### ISSUE TITLE
Automate staging process

### ISSUE THREAD

**Issue by AndreasEK** [valfirst/jbehave-junit-runner#17]
Don't stage manually, but automate the staging process as described:

Manual:
https://docs.sonatype.org/display/repository/sonatype+oss+maven+repository+usage+guide#SonatypeOSSMavenRepositoryUsageGuide-8.ReleaseIt

Automate:
http://www.sonatype.com/books/nexus-book/reference/staging-sect-managing-plugin.html

**Comment by dschneller** [comment]
I noticed that the tags are missing again. We should look into that.

**Comment by AndreasEK** [comment]
which tags? oh, the release tags?
