### ISSUE TITLE
Progress not reported when step with tabular param commented out

### ISSUE THREAD

**Issue by dschneller** [valfirst/jbehave-junit-runner#18]
When a step in a scenario looks like this

```
Given something with a few params:
| Header |
| Value  |
```

everthing works fine.

But when the step is commented out like this:

```
!-- Given something with a few params:
| Header |
| Value  |
```

JBehave executes the steps before and after that, however not progress is reported _at all_ for _any_ steps in _any_ story in the IDE JUnit view.

Version: 1.0.2-SNAPSHOT as of 2012-05-31 17:45 ( commit 19c1b185bdd655654482165e964e46f708b99813 )

**Comment by AndreasEK** [comment]
Don't comment it out! ;) Strange stuff...

I tried to reproduce it with our test case, but it worked fine. There must be something else at play here. How does the step following the commented out step behave, if the prior step is not performed?

```
Scenario: Multiplication with tabular parameters

!-- Given the variables:
| name | value |
|    x |     1 |
|    y |     2 |
|    z |     3 |
When all variables are multiplied
Then the result should be 6
```

**Comment by AndreasEK** [comment]
Hi Daniel,

any luck in reproducing this bug?

Andreas

**Comment by dschneller** [comment]
No. But I have to admit that I did not try again. I am not involved with this project anymore, maybe my successor will see it again. I suggest closing the issue for now.
