### ISSUE TITLE
Version 1.0.1 not available in central (yet)

### ISSUE THREAD

**Issue by mjungsbluth** [valfirst/jbehave-junit-runner#19]
As of now I can't seem to get version 1.0.1 from central (http://repo1.maven.org/maven2/de/codecentric/jbehave-junit-runner/). If the search function of central is used, version 1.0.1 can be found but only in the "Releases" repo. Any ideas?

**Comment by AndreasEK** [comment]
Ok, this is interesting. Let me check.

**Comment by AndreasEK** [comment]
Commented here, that the sync doesn't seem to be running. 

https://issues.sonatype.org/browse/OSSRH-3514?focusedCommentId=160144#comment-160144
