### ISSUE TITLE
Tests failing on master

### ISSUE THREAD

**Issue by MysterAitch** [valfirst/jbehave-junit-runner#228]
Hi,

I just downloaded the project, but running tests on the master branch are failing -- both when running via maven and via IntelliJ IDEA. Is this expected?

![image](https://user-images.githubusercontent.com/1537214/111906392-48e24980-8a48-11eb-99b4-e7b47b7bd1c9.png)

![image](https://user-images.githubusercontent.com/1537214/111906423-6ca58f80-8a48-11eb-8781-b99c6e88df7c.png)

**Comment by MysterAitch** [comment]
Note that checking out tag `v2.3.0` results in the same (or, at least, very similar) test failures:

![image](https://user-images.githubusercontent.com/1537214/111906593-1edd5700-8a49-11eb-86ae-6d3f75826e1f.png)

**Comment by valfirst** [comment]
@MysterAitch some tests may fail on purpose, they are used to check handling of failures in JBehave stories. You can find the actual configuration in `pom.xml`: https://github.com/valfirst/jbehave-junit-runner/blob/c12bc5f05b12131c25207f9607dd29e028ea15b4/pom.xml#L117-L159
