### ISSUE TITLE
How to generate the jbehave-surefire.xml file with parametrised examples

### ISSUE THREAD

**Issue by sergiogq-symphony** [valfirst/jbehave-junit-runner#255]
We are using `JBehave` with `Examples` ([parametrised](https://jbehave.org/reference/stable/parametrised-scenarios.html)) scenarios.

But, when we generate the SurefireReporter file (`withSurefireReporter(new SurefireReporter(this.getClass()))`), the Examples are not inside this file.

Do you have any idea why? Thanks in advance.

**Comment by valfirst** [comment]
@sergiogq-symphony please report the issue here: https://jbehave.atlassian.net/browse/JBEHAVE

**Comment by sergiogq-symphony** [comment]
Hey @valfirst! It says that I am not authorized to create tickets there :(

**Comment by valfirst** [comment]
@sergiogq-symphony are you registered and logged in?

**Comment by sergiogq-symphony** [comment]
Cool, now I was able to report it [here](https://jbehave.atlassian.net/browse/JBEHAVE-1556). Thanks @valfirst

**Comment by valfirst** [comment]
JBehave ticket was created by @sergiogq-symphony: https://jbehave.atlassian.net/browse/JBEHAVE-1556
