### ISSUE TITLE
Deploy to mvn central

### ISSUE THREAD

**Issue by AndreasEK** [valfirst/jbehave-junit-runner#3]
Description is here:
https://docs.sonatype.org/display/repository/sonatype+oss+maven+repository+usage+guide#SonatypeOSSMavenRepositoryUsageGuide-6.CentralSyncRequirement

Ticket for hosting is already created:
https://issues.sonatype.org/browse/OSSRH-3514

**Comment by AndreasEK** [comment]
First steps are made:
https://oss.sonatype.org/content/repositories/snapshots/de/codecentric/jbehave-junit-runner/

**Comment by dschneller** [comment]
Release 1.0.0 is in the Maven Central Repository.
