### ISSUE TITLE
carriage return in the step breaks jbehave-junit-runner

### ISSUE THREAD

**Issue by bdeneuter** [valfirst/jbehave-junit-runner#31]
For some stories we have a carriage return (\r) in a step.
JBehave itself doesn't have any problems with it, but the junit-runner stops showing the junit descriptions

**Comment by skurlow** [comment]
I cannot reproduce this issue with the latest code in master. Do you want to close this? Or can you provide more info on how to reproduce it?

**Comment by bdeneuter** [comment]
Thx, if it is not reproducable anymore, I will close the issue.
