### ISSUE TITLE
Unable to run jbehave .feature file with JUnitReportingRunner

### ISSUE THREAD

**Issue by njagadee** [valfirst/jbehave-junit-runner#34]
Hi - I am using GherkinStoryParser using jbehave. When I use JUnitReportingRunner, only BeforeStories and AfterStories are run and the .feature file is not getting executed. Here is the code and error. Please help. What could be the issue? Any help is much appreciated.

@RunWith(JUnitReportingRunner.class)
public class CalcConfig extends JUnitStories {
public CalcConfig() {
    super();
    JUnitReportingRunner.recommandedControls(configuredEmbedder());
}
    @Override
    public Configuration configuration() {
        Class<? extends Embeddable> embeddableClass = this.getClass();
        return new MostUsefulConfiguration()
                .useStoryParser(new GherkinStoryParser())
                .useStoryLoader(new LoadFromClasspath(embeddableClass))
                .useStoryReporterBuilder(
                        new StoryReporterBuilder().withDefaultFormats()
                                .withFormats(STATS, HTML, TXT, CONSOLE))
                .useParameterControls(
                        new ParameterControls()
                                .useDelimiterNamedParameters(true));
    }
    @Override
    public InjectableStepsFactory stepsFactory() {
        return new InstanceStepsFactory(configuration(), new CalcSteps());
    }
    @Override
    protected List<String> storyPaths() {
        return new StoryFinder().findPaths(
                codeLocationFromClass(this.getClass()), "*_/_.feature", "");
    }

}
============================ Here is the error I am getting:

Failed to run story test/resources/calculator/Calculator.feature java.lang.AbstractMethodError: de.codecentric.jbehave.junit.monitoring.JUnitScenarioReporter.lifecyle(Lorg/jbehave/core/model/Lifecycle;)V at org.jbehave.core.reporters.DelegatingStoryReporter.lifecyle(DelegatingStoryReporter.java:79) at org.jbehave.core.reporters.ConcurrentStoryReporter.lifecyle(ConcurrentStoryReporter.java:137) at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:277) at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220) at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181) at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229) at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201) at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) at java.util.concurrent.FutureTask.run(FutureTask.java:138) at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) at java.lang.Thread.run(Thread.java:680)

(AfterStories)

Generating reports view to '/Documents/workspace/Calculator/jbehave' using formats '[stats, stats, html, txt, console, junitscenarioreporter]' and view properties '{defaultFormats=stats, decorateNonHtml=true, viewDirectory=view, decorated=ftl/jbehave-report-decorated.ftl, reports=ftl/jbehave-reports-with-totals.ftl, maps=ftl/jbehave-maps.ftl, navigator=ftl/jbehave-navigator.ftl, views=ftl/jbehave-views.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl}' Reports view generated with 0 stories (of which 0 pending) containing 0 scenarios (of which 0 pending)

**Comment by zambrovski** [comment]
The problem is with the new snapshot version of JBehave. Since 3.9-SNAPSHOT, JBehave defines this method, which is not yet implemented by the Reporter: http://jbehave.org/reference/latest/javadoc/core/org/jbehave/core/reporters/StoryReporter.html#lifecyle(org.jbehave.core.model.Lifecycle)

I'll create a patch and push it tonight.

**Comment by njagadee** [comment]
Thank you!

**Comment by Kamaraju333** [comment]
Zambrovski , Is the patch mentioned above is pushed .. Still i am facing the issue .

**Comment by britter** [comment]
Is this a duplicate of #38 ? Then it should be fixed in the latest release. @Kamaraju333 which version of jBehave and jbehave-test-runner are you using?

**Comment by Kamaraju333** [comment]
I am using 3.9.1 I am unable to run specific scenario in given stories .

**Comment by britter** [comment]
Which version of the jbehave-test-runner are you using?

**Comment by Kamaraju333** [comment]
Am using thucydidesjunit

**Comment by britter** [comment]
I don't know thucydidesjunit, but it doesn't look like it introduces a dependency onto jbehave-test-runner (http://mvnrepository.com/artifact/net.thucydides/thucydides-junit/0.9.235). Are you sure that you're problem is related to this library (the jbehave-test-runner) at all? If you have are using the jbehave-test-runner, please make sure you're using the latest version (which is 1.1.0).

**Comment by naina971** [comment]
I am using following dependencies still getting error
    compile group: 'junit', name: 'junit', version: '4.12'
    compile 'org.jbehave:jbehave-core:4.3.5'
    compile group: 'com.github.valfirst', name: 'jbehave-junit-runner', version: '2.2.0'
    testCompile group: 'org.mockito', name: 'mockito-core', version: '2.22.0'

Error:- java.lang.AbstractMethodError
	at org.jbehave.core.reporters.DelegatingStoryReporter.beforeScenario(DelegatingStoryReporter.java:58)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.beforeScenario(ConcurrentStoryReporter.java:174)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:957)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:858)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:834)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:418)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:389)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:292)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by valfirst** [comment]
@naina971 , could you please provide a small project to reproduce the issue?

**Comment by naina971** [comment]
When I use JUnitReportingRunner, only BeforeStories and AfterStories are run and the .feature file is not getting executed.

@RunWith(JUnitReportingRunner.class)
public class StoryConfig extends JUnitStories {

    Logger logger = Logger.getLogger(StoryConfig.class.getName());
    ReadProperties readProperties = new ReadProperties();
    GenerateReport generateReport = new GenerateReport();

public StoryConfig() {
        JUnitReportingRunner.recommendedControls(configuredEmbedder());
            configuredEmbedder().useExecutorService(new SameThreadExecutors().create(
                    configuredEmbedder()
                            .embedderControls()
                            .useStoryTimeoutInSecs(600)
            ));
            try {
                 //Required to run stories with annotated meta filters
                configuredEmbedder().useMetaFilters(Arrays.asList(getListOfStoriesToRun().split(",")));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

@Override
    public Configuration configuration() {
        Class<? extends Embeddable> embeddableClass = this.getClass();
        StepCollector stepCollector = new MarkUnmatchedStepsAsPending(new StepFinder(new StepFinder.ByLevenshteinDistance()));
        return new MostUsefulConfiguration()
                .useStepCollector(stepCollector)
                .useStoryLoader(new LoadFromClasspath(embeddableClass))
                .useParameterConverters(new ParameterConverters().addConverters(new ParameterConverters.DateConverter(new SimpleDateFormat("yyyy-MM-dd"))))
                .useStoryReporterBuilder(new StoryReporterBuilder()
                        .withCodeLocation(codeLocationFromClass(embeddableClass))
                        .withFormats(org.jbehave.core.reporters.Format.STATS,
                                org.jbehave.core.reporters.Format.CONSOLE,
                                org.jbehave.core.reporters.Format.HTML,
                                org.jbehave.core.reporters.Format.XML,
                                AsciidoctorStoryReporter.ASCIIDOC)
                        .withDefaultFormats()
                        .withFailureTrace(true));
    }

**Comment by valfirst** [comment]
@naina971, it seems, you are using old version of `AsciidoctorStoryReporter` which is not compatible with JBehave 4.3.5, and as result you see
```
java.lang.AbstractMethodError
at org.jbehave.core.reporters.DelegatingStoryReporter.beforeScenario(DelegatingStoryReporter.java:58)
...
```

**Comment by naina971** [comment]
Thanks it worked.
