### ISSUE TITLE
Please release a version to support latest stable JBehave core release 3.9

### ISSUE THREAD

**Issue by benheap** [valfirst/jbehave-junit-runner#38]
Hi
We really benefit from using your jar to provide us with clearer debugs and runs through eclipse. However we have just upgraded from JBehave-core-3.8 to 3.9 (released mid dec 2013) and found that we cannot use version 1.0.2 with this.

Please could you update jbehave-junit-runner to support jbehave-core-3.9 and junit-4.11?

many thanks

**Comment by britter** [comment]
Hello Ben,

I'll try to have a look at this, this week.

Benedikt

**Comment by kharel** [comment]
Hi,
Any update on this?

Thanks

**Comment by britter** [comment]
@kharel we have fixed this issue in trunk. I've asked the RM to release trunk as 1.1.0, but it depends on how much time he can spare. If he cannot manage to release this until friday, I'll cut the release on friday by myself.

**Comment by kharel** [comment]
thanks a lot britter
can you please notify this thread once v 1.1.0 is deployed?

thanks again,
Kfir

**Comment by britter** [comment]
@kharel yes, I'll notify this thread then.

**Comment by kharel** [comment]
Hi briiter, any update?
Thanks

**Comment by kharel** [comment]
Thanks a lot!

**Comment by Kamaraju333** [comment]
Am using thucydidesjunit
