### ISSUE TITLE
JUnitStory is not supported, only JUnitStories

### ISSUE THREAD

**Issue by dertseha** [valfirst/jbehave-junit-runner#4]
When using the single-story embedder a switch could be done to JUnitStories with not much effort - but it would be great if the runner is capable of handling this case on its own.

**Comment by dschneller** [comment]
Added a patch that should now enable support for JUnitStory subclasses to be run.
Please give it a go, as we do not use it in any of our projects currently, there might be something left to do that I missed.
If so, please reopen this issue.
