### ISSUE TITLE
IntelliJ 13.0.2 Community Edition not showing scenario fails when step fails

### ISSUE THREAD

**Issue by skurlow** [valfirst/jbehave-junit-runner#44]
I have a bunch of stories that I am trying to run using:

@RunWith(JUnitReportingRunner.class)
public class AllStories extends JUnitStories
{
...
}

In my pom.xml I have:

```
    <dependency>
        <groupId>de.codecentric</groupId>
        <artifactId>jbehave-junit-runner</artifactId>
        <version>1.1.0</version>
    </dependency>
```

The screenshot shows a step that has failed yet the scenario shows as passed. What could be causing this?
![capture](https://f.cloud.github.com/assets/676367/2444098/95133658-ae49-11e3-95ec-e921045846b3.PNG)

**Comment by vincent-kennedy** [comment]
I am also experiencing this issue with Intellij 13.0.2 Ultimate.

To add a little more info - one of my scenarios does fail, yet the scenario highlighted in the runner is not actaully the scenario that failed.

Smells like a threading issue....

**Comment by skurlow** [comment]
I have started working on resolving this issue in my fork

**Comment by AndreasEK** [comment]
If you don't mind, I'd like to remove the fix since:
* recent intelliJ versions don't have the problem any longer and
* it introduces two additional failed tests (story failed, scenario failed)
