### ISSUE TITLE
Missing steps are not reported, related scenarios are OK

### ISSUE THREAD

**Issue by dertseha** [valfirst/jbehave-junit-runner#5]
If a new scenario is added with missing steps (no binding code exists), the steps are not added to the report tree and even worse, the scenario is marked OK.

Personally I’d want those to be reported as failures (with a  stub implementation text extractable from the failure trace) – but I can imagine others might not want this behaviour; Is there a possibility to add configuration options to the JUnitReportingRunner?

The missing steps should at least be reported like pending steps.

**Comment by dschneller** [comment]
Pending steps are now reported as 'ignored' in JUnit. This and the ability to include/exclude ignorables (comments) from the tree will be added in a future release.
