### ISSUE TITLE
Make use of Travis CI

### ISSUE THREAD

**Issue by britter** [valfirst/jbehave-junit-runner#56]
Travis CI is a nice and easy way to get a project into a CI environment. Since it is for free, we should activate it for this project. This may require getting in touch with the owner of the codecentric github account. Docs on Travis CI can be found [here](http://docs.travis-ci.com/user/getting-started/).

**Comment by visusnet** [comment]
I guess, we should focus on this issue first before we continue with other issues to prevent broken branches from being merged.

**Comment by britter** [comment]
Good idea. I'll get in touch with @CodingFabian, he should have the karma to activate the project on travis-ci

**Comment by visusnet** [comment]
Karma... and administrator privileges won't hurt.

**Comment by CodingFabian** [comment]
Karma has been distributed
