### ISSUE TITLE
Remove SpringReportingJUnitRunner

### ISSUE THREAD

**Issue by britter** [valfirst/jbehave-junit-runner#58]
The SpringReportingJUnitRunner hasn't been well thought out in the first place. We shouldn't push something like this out. Beside that, it looks like [Spring will provide a test rule](https://jira.spring.io/browse/SPR-7731) soon, making it possible to use the jbehave-junit-runner in conjunction with DI.

**Comment by skurlow** [comment]
It is already possible to use the runner with Spring DI. Excerpt from my runner is:

@RunWith(JUnitReportingRunner.class)
public class StoryRunner extends JUnitStories implements ApplicationContextAware {
    public StoryRunner() {
        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("/spring/function-context.xml");
        setApplicationContext(applicationContext);
    }
// etc
}

**Comment by visusnet** [comment]
You can use applicationContext to get beans, yes, but you cannot autowire beans directly into your StoryRunner. That's where a SpringContextRule comes in. You can find some of them in the wild, e.g.:
https://jira.spring.io/secure/attachment/17655/SpringContextRule.java

**Comment by britter** [comment]
For now you can get an `AutowireCapableFactoryBean` from the `ApplicationContext` and use the `autowireBean(Object)` method to inject members into the class. (see http://stackoverflow.com/questions/3813588/how-to-inject-dependencies-into-a-self-instantiated-object-in-spring)

**Comment by britter** [comment]
I've created #62 for documenting this.
