### ISSUE TITLE
Test count is wrong in combination with missing steps

### ISSUE THREAD

**Issue by dertseha** [valfirst/jbehave-junit-runner#7]
In relation to #5, the count of run/found tests is wrong when a story contains missing steps:

When a scenario contains only missing steps, nothing is counted to the total, but an additional run is counted.

``` Gherkin
Given a story with only one scenario consisting of missing steps
When the story is run in JUnit
Then 3/2 runs are reported
```

Considering missing steps are to be reported:

``` Gherkin
Then 5/5 runs should be reported
```

(The 2 extra runs are for the Before/After Stories steps)

This might be a side-effect of an empty tree entry for test descriptions, automatically solved when #5 is solved.

**Comment by dschneller** [comment]
Indeed fixed with issue #5 (which has been closed, too).
