### ISSUE TITLE
Dependency on org.junit.runner.RunWith conflicts with BDD's philosophy of not being "tests"

### ISSUE THREAD

**Issue by mosofsky-netbase** [valfirst/jbehave-junit-runner#74]
jbehave-junit-runner suggests using @org.junit.runner.RunWith(JUnitReportingRunner.class).  However http://jbehave.org/reference/stable/examples-philosophy.html suggests that JBehave configuration and code belongs in src/main instead of src/test.  I suspect people would normally scope junit to pertain just to test in their Maven pom.xml file like this:

```
<dependency>
  <groupId>junit</groupId>
  <artifactId>junit</artifactId>
  <version>4.11</version>
  <scope>test</scope>
</dependency>
```

However, if the JUnitStories sublcass that's annotated with @org.junit.runner.RunWith(JUnitReportingRunner.class) is under src/main instead of src/test then there's a conflict.

See more at http://stackoverflow.com/questions/27629791/adding-runwith-for-jbehave-junit-runner-breaks-jbehave-build-using-maven

**Comment by skurlow** [comment]
http://jbehave.org/reference/stable/examples-philosophy.html states  "This is why it is recommendable for integration testing to have a separate module and to place the behaviour code in src/main"

When you look at my quick start project in https://bitbucket.org/skurlow/qs_jbehave/overview you will see the acceptance test code is in a separate module called bdd. The system under test by the acceptance test code is in the app module.

If there is any complicated acceptance test code in src/main then I have seen sometimes unit tests written to help ensure the acceptance test code is correct in src/test of the bdd module.

Deploy the app module to QA and Production envs and the bdd module will never be deployed to a Production env.
