### ISSUE TITLE
JUnitScenarioReporter throws NPE when story file name contains parentheses

### ISSUE THREAD

**Issue by valfirst** [valfirst/jbehave-junit-runner#80]
JUnitScenarioReporter throws NPE when story file name contains parentheses.

```
Caused by: java.lang.NullPointerException
at de.codecentric.jbehave.junit.monitoring.JUnitScenarioReporter.beforeScenario(JUnitScenarioReporter.java:163)
at org.jbehave.core.reporters.DelegatingStoryReporter.beforeScenario(DelegatingStoryReporter.java:55)
...
```

The source of issue is check in JUnitScenarioReporter (line 97):

```
storyDescription.getDisplayName().equals(story.getName())
```

It should be something like:

```
JUnitDescriptionGenerator jUnitDescriptionGenerator...
...
storyDescription.getDisplayName().equals(jUnitDescriptionGenerator.getJunitSafeString(story.getName()))
```

Could you please fix it?

**Comment by britter** [comment]
Thank you for the report!

> Could you please fix it?

Can you please provide a fix as PR? ;-)

**Comment by valfirst** [comment]
Does anybody review changes and merge pull-request? Or is this project dead?

**Comment by valfirst** [comment]
Fixed: https://github.com/codecentric/jbehave-junit-runner/commit/50cfd3a1e8ed8754fe35436ebec8a49ee0c42cd0
