### ISSUE TITLE
Throws RuntimeException on scenario failure instead of java.lang.AssertionError

### ISSUE THREAD

**Issue by iriusrisk** [valfirst/jbehave-junit-runner#81]
ConcurrentStoryReporter.java throws a RuntimeException when a scenario fails.  
This results in incorrect behaviour for wrapper tools like ant junit.  I need ant to exit with status code 1 on error, but with status code 0 on failure.

With the current behaviour of ConcurrentStoryReporter it interprets failures as if they were errors.

**Comment by britter** [comment]
Pull requests welcome!

**Comment by britter** [comment]
Fixed with #82
