### ISSUE TITLE
bad checksum on repo1.maven.org

### ISSUE THREAD

**Issue by SammyJanssens** [valfirst/jbehave-junit-runner#86]
i get following error when trying to download the latest version of jbehave-junit-runner:

``` json
{
errors: [
{
status: 409,
message: "Rejected artifact download request: Checksum policy 'GEN_IF_ABSENT' rejected the artifact 'repo1-cache:de/codecentric/jbehave-junit-runner/1.2.0/jbehave-junit-runner-1.2.0.pom'. Checksums info: ChecksumsInfo{checksums={SHA-1=ChecksumInfo{type=SHA-1, original='6c4e5ac335861416f37e83cacb30ca7544e099c3', actual='ef2a0dae53029dfaa1cf0a851bc98d3a2ce66f67'}, MD5=ChecksumInfo{type=MD5, original='12a7bf696a92c4da51062a4293c24196', actual='d75c04e884c445e51a66d7a71e248400'}}}"
}
]
}
```

i've checked the repo in i find it strange the md5&sha1 hash have a different modified date 
![new issue codecentricjbehave-junit-runner - google chrome](https://cloud.githubusercontent.com/assets/435376/11630723/f8b5a704-9cfe-11e5-863d-f127d8b00091.jpg)
currently the hashes are
md5: 12a7bf696a92c4da51062a4293c24196
sha1: 6c4e5ac335861416f37e83cacb30ca7544e099c3

but when i download the pom and check the hash ( http://onlinemd5.com/ ) i get different results.
md5: D75C04E884C445E51A66D7A71E248400
sha1: EF2A0DAE53029DFAA1CF0A851BC98D3A2CE66F67

it seems the checksums are incorrect on the mvn repository

**Comment by valfirst** [comment]
@SammyJanssens , please use new release: https://repo1.maven.org/maven2/com/github/valfirst/jbehave-junit-runner/2.0.0/
