### ISSUE TITLE
Not showing correct test names in IntelliJ

### ISSUE THREAD

**Issue by cstroe** [valfirst/jbehave-junit-runner#87]
I'm using IntelliJ Community 15.0.4 with [this project on the jbehave branch](https://github.com/cstroe/svndumpapi/tree/jbehave).

When running the `RunStories` runner, this is how it shows up in IntelliJ:

![junit-steps](https://cloud.githubusercontent.com/assets/1182093/13827875/c31a379a-eb8c-11e5-9fbf-bf33b18ac91e.png)

Several issues:
- Story names don't come through, instead I just see `story` instead of `content_chunk.story`
- Scenario names are `<no name>`
- The steps names include the class name `ContentChunkImplSteps`

I'm using JUnit 4.11, but I also tried JUnit 4.12 and that didn't change it.  Is there something wrong that I'm missing?

**Comment by cstroe** [comment]
Also seeing this with IntelliJ 2016.1

**Comment by metivier** [comment]
Hi,

I have the same issue for the story name. All the story are named "story", instead of the file name. It is complicated to find which story failed when you run a set of stories.

But for me the scenario names are displayed.

(idea 2016.1.3)

**Comment by dbelahcen** [comment]
Hi,

As well as metivier, I can see scenarios names but not story names. Did somebody overcome this issue?

About scenario names, I could reproduce the issue when having a period at the end of the scenario description.

Having :
      Scenario: the best scenario ever
will display scenario name properly.
BUT having: 
      Scenario: the best scenario ever.
won't be displayed because of the period at the end.

Hope that helps
Daniel.

**Comment by Nom1fan** [comment]
Experiencing the same thing... Thanks Daniel for helping improve this a bit!

**Comment by GijsvanDulmen** [comment]
Same thing on IntelliJ 2016.3.4 with jbehave-junit-runner 1.2.1.

**Comment by matozoid** [comment]
Same on Intellij 2017.2.3 with jbehave-junit-runner 2.0.0

**Comment by krm1312** [comment]
Workaround below.  IntelliJ is truncating the name as if it is a classname I believe, so, you end up with just "story". 

```java
config.useStoryParser(new RegexStoryParser(config.keywords(), config.storyLoader(), config.tableTransformers()) {
            @Override
            public Story parseStory(String storyAsText, String storyPath) {
                Story story = super.parseStory(storyAsText, storyPath);
                story.namedAs("Story: " + story.getName().replaceAll(".story$", ""));
                return story;
            }
        });
```
