### ISSUE TITLE
Customize output monitor

### ISSUE THREAD

**Issue by aquintiliano** [valfirst/jbehave-junit-runner#89]
Hi, I am trying to customize the output monitor, I want to show the name of the story, instead of the text "story" and I want to show each step with format "[class of step]: [name of step]", how can I do that? I can't figure out what exactly shows the text in that monitor

**Comment by valfirst** [comment]
@aquintiliano, 

> I want to show the name of the story, instead of the text "story"

could you please try the latest release?

>I want to show each step with format "[class of step]: [name of step]", how can I do that? I can't figure out what exactly shows the text in that monitor

could you provide more details of what you are trying to achieve?
