### ISSUE TITLE
Comments in scenario are reported as ignored

### ISSUE THREAD

**Issue by mbocek** [valfirst/jbehave-junit-runner#90]
Shouldn't be comments simply skipped?

**Comment by valfirst** [comment]
@mbocek, I think it's JBehave behavior, jbehave-junit-runner just uses JBehave. If you think it's an issue, please, file JBehave ticket. We faced with the same issue and fixed it in [JBehave fork](https://github.com/valfirst/jbehave-core/commit/6112a7eda480a084655e2ecd2852cb763ceb41e3). I can create a pull-request for Jbehave core based on my fork.

**Comment by mbocek** [comment]
@valfirst i see. Scenario object holding all steps and ignore steps are also in the collection. Please send the PR to jbehave and we will see. Please add PR number to this thread. Otherwise maybe we can exclude ignore steps whose starting with comment prefix, right?

**Comment by valfirst** [comment]
@mbocek ,
JBehave issue: https://jbehave.atlassian.net/browse/JBEHAVE-1191
PR: https://github.com/jbehave/jbehave-core/pull/130

**Comment by jcarnus** [comment]
Hi, In jbehave 4.1+, the StoryReporter has been changed, I can submit a PR to correct this but is someone still looking at this projet to release a new version quickly ?

Thanks

**Comment by valfirst** [comment]
hi @jcarnus , please, take a look at PR https://github.com/codecentric/jbehave-junit-runner/pull/96, does it address your needs?

But unfortunately I'm not the owner of the project and can't release it.

**Comment by jcarnus** [comment]
Seems that no because the https://github.com/jbehave/jbehave-core/blob/master/jbehave-core/src/main/java/org/jbehave/core/reporters/StoryReporter.java now has a 

void comment(String step);

So the implementation doesn't match the interface,

Jeremy

**Comment by valfirst** [comment]
@jcarnus, please, take a look at [JUnitScenarioReporter.java#L26](https://github.com/codecentric/jbehave-junit-runner/blob/master/src/main/java/de/codecentric/jbehave/junit/monitoring/JUnitScenarioReporter.java#L26), it uses NullStoryReporter which [contains the default empty implementation](https://github.com/jbehave/jbehave-core/blob/master/jbehave-core/src/main/java/org/jbehave/core/reporters/NullStoryReporter.java#L38), so technically there is no compatibility issue at this area.

As for conceptual part of the question, I don't really think jbehave-junit-runner should take care of comments (ignored steps are handled in a proper way as it was before). The original idea of [JBEHAVE-1191](https://jbehave.atlassian.net/browse/JBEHAVE-1191) is to have clear distinguishment of ignored steps and comments.

**Comment by jcarnus** [comment]
Correct, but the latest deployed version 1.2.0 doesn't contains this version of code. So the 1.2 version is not compatible with jBhevae 4.1.1

**Comment by valfirst** [comment]
@jcarnus, that's true, I've [tried to ping "potential" maintainers](https://github.com/codecentric/jbehave-junit-runner/pull/96#issuecomment-311033001) - no success for now. Also my previous experience shows that PRs can wait merging for years in this repo. So you can try asking/pinging owners if you know them ... or it could be a good time for the next fork 😄

**Comment by valfirst** [comment]
@jcarnus, @mbocek, the new version is released:
```xml
<dependency>
    <groupId>com.github.valfirst</groupId>
    <artifactId>jbehave-junit-runner</artifactId>
    <version>2.0.0</version>
</dependency>
```
